language: scala
scala:
- 2.11.7
python:
- '2.7'
before_install:
- sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
- sudo apt-get update -qq
install:
- sudo apt-get install -qq mosquitto mosquitto-clients
- wget -c -N --no-verbose http://d3kbcqa49mib13.cloudfront.net/spark-1.5.2-bin-hadoop2.6.tgz
- tar xzf spark-1.5.2-bin-hadoop2.6.tgz -C $HOME
before_script:
- mosquitto -p 1883 1>/dev/null 2>/dev/null &
script:
- jdk_switcher use oraclejdk8
- sudo $HOME/spark-1.5.2-bin-hadoop2.6/sbin/start-master.sh
- sudo $HOME/spark-1.5.2-bin-hadoop2.6/sbin/start-slave.sh localhost:7077
- export SPARK_HOME=$HOME/spark-1.5.2-bin-hadoop2.6/
- export PYTHONPATH=$SPARK_HOME/python/:$SPARK_HOME/python/lib/py4j-0.8.2.1-src.zip:$PYTHONPATH
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/Hydrospheredata/mist/src/main/python
- sbt ++$TRAVIS_SCALA_VERSION $TEST
- sbt -Dconfig.file=/home/travis/build/Hydrospheredata/mist/configs/travis.conf scoverage:test
- sbt coveralls
env:
  global:
    secure: f+Kg5LkG5fBsJ5/V7dOxWGMUeWPBU8vUNDk0HsytNtm9mTnospTiFykoxiXbKNhVlmfhmAsyseIcKIrFwSoz/6rlJXiHYdTeH/DSoCa/JLDLMn/7zJp8v6lwer2KEpc+cnUiG5TMR1QmGJ2yVrw1DrwUqs9hBrWNP1bmr1wXGgrde56fnFXKy6YlToUWqtqHn0lMYaV/gBH7jdCdC4Q3n1FlAe9a8x7Lecy3sm489Fpyf6MuekdrulmW15YXJ71XAiEwGA24zxqOd5Pp2Vcyg2UNVtTyjyqlybhX65Ov/hzup44xjdyEFW0u7jt7AdIKTXBrHVvfoLg5c52Jltr+yhJA37zgntWRIA1pRWxJXOpfL5zaICLSVovS0J4xfdPOgK6o4kCVGBNQdy/jeKyFtPAE2SFjDQ4pCeSBUJ3uk0w2MEnyTluZHg2vQtjKXDVsLNxD6sr6UPUURgMm8d7BR8tqVzCUU5kwdR1WQVzkNEmurXv0Zuohjc1NK8f9Qwqd7DlEAtdtpSVg1F9V5qzOeEGq0aYy6Uu2R8WEN8SiZITdVgL0LZQo12kOPqoSJLNERx0KFNIaqBtsuqnZirdCPgF7FeZou5iN5sxVSX7OL8/AnuhV/W8R/V0n2K90rXY6OXfOwl4ojVxc7uoavHmLzhmfDVUcQv22AXwicT3DQRU=
